### ISSUE TITLE
Cocaine::ExitStatusError when I switch from paperclip-ffmpeg 1.0.1 to 1.2.0

### ISSUE THREAD

**Issue by casertap** [owahab/paperclip-ffmpeg#60]
Everything is fine with the version 1.0.1 but when I switch to version 1.2.0 I get this stack:

````
Command :: PATH=/usr/local/bin/ffmpeg:$PATH file -b --mime '/var/folders/43/t8s11k6d145c4wtwfpnbxh640000gn/T/6c84cbd30cf9350a990bad2bcc1bec5f20150205-9509-104fieg.MOV'
sh: -c: line 0: syntax error near unexpected token `then'
sh: -c: line 0: `PATH=/usr/local/bin/ffmpeg:$PATH if command -v ffprobe 2>/dev/null; then echo "true"; else echo "false"; fi'
Could not log "process_action.action_controller" event. Encoding::UndefinedConversionError: "\xEA" from ASCII-8BIT to UTF-8 [...]

Cocaine::ExitStatusError - Command 'PATH=/usr/local/bin/ffmpeg:$PATH if command -v ffprobe 2>/dev/null; then echo "true"; else echo "false"; fi' returned 2. Expected 0
Here is the command output:

:
  cocaine (0.5.5) lib/cocaine/command_line.rb:92:in `run'
  paperclip-ffmpeg (1.2.0) lib/paperclip_processors/ffmpeg.rb:249:in `detect_command'
  paperclip-ffmpeg (1.2.0) lib/paperclip_processors/ffmpeg.rb:233:in `detect_ffprobe_or_avprobe'
  paperclip-ffmpeg (1.2.0) lib/paperclip_processors/ffmpeg.rb:183:in `identify'
  paperclip-ffmpeg (1.2.0) lib/paperclip_processors/ffmpeg.rb:36:in `initialize'
  paperclip (4.2.1) lib/paperclip/processor.rb:33:in `make'
  paperclip (4.2.1) lib/paperclip/attachment.rb:522:in `block in post_process_style'
  paperclip (4.2.1) lib/paperclip/attachment.rb:521:in `post_process_style'
  paperclip (4.2.1) lib/paperclip/attachment.rb:512:in `block in post_process_styles'
  paperclip (4.2.1) lib/paperclip/attachment.rb:511:in `post_process_styles'
  paperclip (4.2.1) lib/paperclip/attachment.rb:503:in `block (2 levels) in post_process'

```
If i try to execute the command in my terminal:

````
$ PATH=/usr/local/bin/ffmpeg:$PATH if command -v ffprobe 2>/dev/null; then echo "true"; else echo "false"; fi
bash: syntax error near unexpected token `then'
````

**Comment by vinnividivicci** [comment]
It's worth noting that paperclip_ffmpeg is being deprecated (see REAME) in favor of https://github.com/ruby-av/paperclip-av-transcoder

However, I'm still using paperclip_ffmpeg and it's working fine on both my dev and production servers (Ubuntu 14+)

Make sure you have libav-tools installed (a.k.a avconv) which is now supported by this gem.

Hope that helps!

**Comment by itsSaad** [comment]
i have lib installed via brew `brew install libav` but its still the same
and i have `1.2.0` version of this gem?

**Comment by owahab** [comment]
This project has been deprecated in favor of [paperclip-av-transcoder](https://github.com/ruby-av/paperclip-av-transcoder).
